
spwawn-locations:
  red:
    x: -26
    y: 0
    z: 0
    yaw: 90
    pitch: 0
  
  yellow:
    x: 26
    y: 0
    z: 0
    yaw: -90
    pitch: 0

arena-fill:
  '1':
    block: air
    pos1: 31 -64 24
    pos2: -31 99 -24
  
  # Red spawn platform
  '2':
    block: bedrock
    pos1: -28 -1 2
    pos2: -24 -64 -2
  '3':
    block: red_wool
    pos1: -28 -1 2
    pos2: -24 -1 -2
  '4':
    block: bedrock
    pos1: -27 -1 1
    pos2: -25 -1 -1
  
  # Yellow spawn platform
  '5':
    block: bedrock
    pos1: 28 -1 2
    pos2: 24 -64 -2
  '6':
    block: yellow_wool
    pos1: 28 -1 2
    pos2: 24 -1 -2
  '7':
    block: bedrock
    pos1: 27 -1 1
    pos2: 25 -1 -1  

saved-layouts:
